Repository Likelion-YeungNam-Univ/YU-LikeLion-iOS, pull requests merged in 2024-03, with the labels that each got.

#24 [fix] 🐛 MyPageView 바인딩문제 해결완료
  YU-LikeLion-iOS.xcodeproj/project.xcworkspace/xcuserdata/yunganglog.xcuserdatad/UserInterfaceState.xcuserstate
  YU-LikeLion-iOS.xcodeproj/xcuserdata/yunganglog.xcuserdatad/xcschemes/xcschememanagement.plist
  YU-LikeLion-iOS/Assets.xcassets/DepartmentIcon.imageset/DepartmentIcon@2x.png
  YU-LikeLion-iOS/ContentView.swift
  YU-LikeLion-iOS/Model/MyPage/User.swift
  YU-LikeLion-iOS/View/MyPage/ImagePickerView.swift
  YU-LikeLion-iOS/View/MyPage/ModifyMyPageView.swift
  YU-LikeLion-iOS/View/MyPage/MyPageView.swift
Labels: development, help wanted, fix

#28 feat : :sparkles: MyPage 이미지 데이터 연동
  YU-LikeLion-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YU-LikeLion-iOS.xcodeproj/project.xcworkspace/xcuserdata/aushinyan.xcuserdatad/UserInterfaceState.xcuserstate
  YU-LikeLion-iOS.xcodeproj/xcuserdata/aushinyan.xcuserdatad/xcschemes/xcschememanagement.plist
  YU-LikeLion-iOS/ContentView.swift
  YU-LikeLion-iOS/View/MyPage/ModifyMyPageView.swift
  YU-LikeLion-iOS/View/MyPage/MyPageView.swift
Labels: development

#29 [fix] :construction: 게시판 tabView 문제
  YU-LikeLion-iOS.xcodeproj/project.xcworkspace/xcuserdata/aushinyan.xcuserdatad/UserInterfaceState.xcuserstate
  YU-LikeLion-iOS/ContentView.swift
  YU-LikeLion-iOS/View/Board/DetailBoardView.swift
  YU-LikeLion-iOS/View/Board/MainBoardView.swift
Labels: development, help wanted

#30 [feat] ✨ Apple Auth 연결 구현
  YU-LikeLion-iOS.xcodeproj/project.pbxproj
  YU-LikeLion-iOS.xcodeproj/project.xcworkspace/xcuserdata/yunganglog.xcuserdatad/UserInterfaceState.xcuserstate
  YU-LikeLion-iOS/ContentView.swift
  YU-LikeLion-iOS/View/Welcome/WelcomeView.swift
  YU-LikeLion-iOS/ViewModel/LoginViewModel.swift
  YU-LikeLion-iOS/YU-LikeLion-iOS.entitlements
Labels: development, test
